### ISSUE TITLE
ClassCastException in IconGenerator when using with Google analogy

### ISSUE THREAD

**Issue by mohaxspb** [SupasinTatiyanupanwong/huawei-maps-utils#1]
Hello! 

Could you, please, release a new version with small fix?

There is a situation, when using this lib with google analog in IconGenerator layout is loaded. Then, custom view (RotateLayout) from this layout casted to RotateLayout. And there can be ClassCastException, if layout file is loaded from incorrect lib.

So fix can be simple - just rename layout.  I mean file `amu_text_bubble.xml`

**Comment by mohaxspb** [comment]
@SupasinTatiyanupanwong hello again!

I've created PullRequest (https://github.com/SupasinTatiyanupanwong/huawei-maps-utils/pull/2) with layout file renaming. This will fix issue. Could you, please, merge it and upload new version to maven with this fix?

Thanks in advance!

**Comment by SupasinTatiyanupanwong** [comment]
Hi!

Thanks, I'll check and release it soon.

Sorry for late response tho. Strangely that I didn't receive any notification from your issue #1.
